version: '3'

services:
  server:
    build: ./server
    expose:
      - ${SERVER_PORT}
      - ${SERVER_SECPORT}
    environment:
      API_HOST: ${API_HOST}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_SECPORT: ${SERVER_SECPORT}
      REACT_PORT: ${REACT_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_SECPORT}:${SERVER_SECPORT}
    volumes:
      - ./server:/app/server
